# Generated by Django 4.0.4 on 2022-04-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfiles_alter_project_summarize_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFiles',
            new_name='ProjectFile',
        ),
    ]
