# Generated by Django 4.0.4 on 2022-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbreviated',
            field=models.CharField(default='bla', help_text='4 caractère max', max_length=4, unique=True, verbose_name='Clé'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
