# Generated by Django 4.0.4 on 2022-04-13 08:33

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectfile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='image',
            field=models.FileField(upload_to=projects.models.get_upload_path),
        ),
    ]
