# Generated by Django 4.0.4 on 2022-04-12 08:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_category_abbreviated_alter_category_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='summarize',
            field=models.CharField(default='null', help_text='80 caractères max', max_length=80, verbose_name='Résumer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
