# Generated by Django 4.0.4 on 2022-04-13 20:42

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmetric',
            name='download_month',
            field=models.CharField(blank=True, default='Non communiquer', max_length=200, null=True, verbose_name='Nombre de téléchargement'),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='download_proof',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='revenue_month',
            field=models.CharField(blank=True, default='Non communiquer', max_length=200, null=True, verbose_name='Revenue mensuel'),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='revenue_proof',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='viewer_month',
            field=models.CharField(blank=True, default='Non communiquer', max_length=50, null=True, verbose_name='Visiteur par mois'),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='viewer_proof',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_upload_path),
        ),
    ]
