# Generated by Django 4.0.4 on 2022-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectmetric_download_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
