# Generated by Django 4.0.4 on 2022-04-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectimage_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='alt',
        ),
    ]
