# Generated by Django 4.0.4 on 2022-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_projectimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'image"),
        ),
    ]
