# Generated by Django 4.0.4 on 2022-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
