# Generated by Django 4.0.4 on 2022-04-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_category_color_alter_order_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
