# Generated by Django 4.0.4 on 2022-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_ordered_project_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
